/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "student.dashboard": [],
    "login": [],
    "login.post": [],
    "register": [],
    "register.post": [],
    "logout": [],
    "users.index": [],
    "users.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.create": [],
    "users.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "role.index": [],
    "role.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "role.create": [],
    "role.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "role.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "role.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "roleUser.index": [],
    "roleUser.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "roleUser.create": [],
    "roleUser.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "roleUser.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "roleUser.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permission.index": [],
    "permission.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permission.create": [],
    "permission.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permission.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permission.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permissionRole.index": [],
    "permissionRole.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permissionRole.create": [],
    "permissionRole.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permissionRole.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permissionRole.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "subject.index": [],
    "subject.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "subject.create": [],
    "subject.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "subject.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "subject.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "question.index": [],
    "question.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "question.create": [],
    "question.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "question.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "question.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "questionOption.index": [],
    "questionOption.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "questionOption.create": [],
    "questionOption.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "questionOption.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "questionOption.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "quiz.index": [],
    "quiz.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "quiz.create": [],
    "quiz.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "quiz.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "quiz.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "quizQuestion.index": [],
    "quizQuestion.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "quizQuestion.create": [],
    "quizQuestion.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "quizQuestion.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "quizQuestion.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attempt.index": [],
    "attempt.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attempt.create": [],
    "attempt.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attempt.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attempt.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "answer.index": [],
    "answer.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "answer.create": [],
    "tag.index": [],
    "tag.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "tag.create": [],
    "tag.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "tag.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "tag.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "questionTag.index": [],
    "questionTag.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "questionTag.create": [],
    "questionTag.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "questionTag.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "questionTag.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "student.quizzes.show": [
        {
            "name": "quiz",
            "required": true,
            "binding": "id"
        }
    ],
    "student.quizzes.start": [
        {
            "name": "quiz",
            "required": true,
            "binding": "id"
        }
    ],
    "student.attempts.take.single": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        },
        {
            "name": "questionIndex",
            "required": true
        }
    ],
    "student.attempts.submit.single": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        },
        {
            "name": "questionIndex",
            "required": true
        }
    ],
    "student.attempts.submit": [
        {
            "name": "attempt",
            "required": true
        }
    ],
    "student.attempts.index": [],
    "student.attempts.show": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        }
    ],
    "student.attempts.resume": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.dashboard": [],
    "admin.users.index": [],
    "admin.users.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.create": [],
    "admin.users.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roles.index": [],
    "admin.roles.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roles.create": [],
    "admin.roles.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roles.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roles.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roleUsers.index": [],
    "admin.roleUsers.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roleUsers.create": [],
    "admin.roleUsers.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roleUsers.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roleUsers.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.permissions.index": [],
    "admin.permissions.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.permissions.create": [],
    "admin.permissions.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.permissions.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.permissions.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.permissionRoles.index": [],
    "admin.permissionRoles.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.permissionRoles.create": [],
    "admin.permissionRoles.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.permissionRoles.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.permissionRoles.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.subjects.index": [],
    "admin.subjects.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.subjects.create": [],
    "admin.subjects.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.subjects.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.subjects.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.index": [],
    "admin.questions.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.create": [],
    "admin.questions.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questionOptions.index": [],
    "admin.questionOptions.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questionOptions.create": [],
    "admin.questionOptions.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questionOptions.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questionOptions.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizzes.index": [],
    "admin.quizzes.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizzes.create": [],
    "admin.quizzes.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizzes.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizzes.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizQuestions.index": [],
    "admin.quizQuestions.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizQuestions.create": [],
    "admin.quizQuestions.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizQuestions.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizQuestions.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.attempts.index": [],
    "admin.attempts.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.attempts.create": [],
    "admin.attempts.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.attempts.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.attempts.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.answers.index": [],
    "admin.answers.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.answers.create": [],
    "admin.tags.index": [],
    "admin.tags.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.tags.create": [],
    "admin.tags.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.tags.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.tags.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questionTags.index": [],
    "admin.questionTags.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questionTags.create": [],
    "admin.questionTags.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questionTags.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questionTags.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
