/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.post": [],
    "register": [],
    "register.post": [],
    "logout": [],
    "student.dashboard": [],
    "student.subjects.notes.embed": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "student.subject.quizzes": [
        {
            "name": "id",
            "required": true
        }
    ],
    "student.subjects.notes.download": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "student.subjects.notes.preview": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "student.subjects.notes.officeFrame": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "student.adaptive.create": [],
    "student.adaptive.generate": [],
    "student.adaptive.index": [],
    "student.adaptive.myChallenges": [],
    "student.adaptive.toggleVisibility": [
        {
            "name": "quiz",
            "required": true,
            "binding": "id"
        }
    ],
    "student.questions.tagsBySubject": [
        {
            "name": "subjectId",
            "required": false
        }
    ],
    "student.quizzes.show": [
        {
            "name": "quiz",
            "required": true,
            "binding": "id"
        }
    ],
    "student.quizzes.start": [
        {
            "name": "quiz",
            "required": true,
            "binding": "id"
        }
    ],
    "student.quizzes.leaderboard": [
        {
            "name": "quiz",
            "required": true,
            "binding": "id"
        }
    ],
    "student.attempts.take.single": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        },
        {
            "name": "questionIndex",
            "required": true
        }
    ],
    "student.attempts.submit.single": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        },
        {
            "name": "questionIndex",
            "required": true
        }
    ],
    "student.attempts.submit": [
        {
            "name": "attempt",
            "required": true
        }
    ],
    "student.attempts.index": [],
    "student.attempts.show": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        }
    ],
    "student.attempts.resume": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        }
    ],
    "student.attempts.complete": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        }
    ],
    "student.attempts.archive": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        }
    ],
    "student.attempts.unarchive": [
        {
            "name": "attempt",
            "required": true,
            "binding": "id"
        }
    ],
    "student.questions.flagged": [],
    "student.questions.flag": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "student.questions.unflag": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "student.questions.report": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "student.questions.unreport": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.reports.show": [
        {
            "name": "report",
            "required": true
        }
    ],
    "student.charts.index": [],
    "admin.subjects.notes.embed": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.dashboard": [],
    "admin.users.role": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.index": [],
    "admin.users.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.create": [],
    "admin.users.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.subjects.index": [],
    "admin.subjects.create": [],
    "admin.subjects.bulkDestroy": [],
    "admin.subjects.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.subjects.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.subjects.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.subjects.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.subjects.notes.store": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.subjects.notes.destroy": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.subjects.notes.download": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.subjects.notes.preview": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.subjects.notes.officeFrame": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        },
        {
            "name": "note",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.questions.import": [],
    "admin.questions.index": [],
    "admin.questions.ids": [],
    "admin.questions.createForm": [],
    "admin.questions.create": [],
    "admin.questions.review.index": [],
    "admin.questions.myReview.index": [],
    "admin.questions.bulkAssign": [],
    "admin.questions.bulkChangeState": [],
    "admin.questions.bulkDestroy": [],
    "admin.questions.tagsBySubject": [
        {
            "name": "subjectId",
            "required": false
        }
    ],
    "admin.questions.bySubject": [
        {
            "name": "subjectId",
            "required": true
        }
    ],
    "admin.questions.bySubjects": [],
    "admin.questions.adaptive": [],
    "admin.questions.assign": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.unassign": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.changeState": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.resetToInitial": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.questions.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizzes.index": [],
    "admin.quizzes.createForm": [],
    "admin.quizzes.create": [],
    "admin.quizzes.bulkDestroy": [],
    "admin.quizzes.adaptive": [],
    "admin.quizzes.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizzes.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizzes.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizzes.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.quizzes.questions.destroy": [
        {
            "name": "quiz",
            "required": true
        },
        {
            "name": "question",
            "required": true
        }
    ],
    "quizzes.questions.updateOrder": [
        {
            "name": "quiz",
            "required": true,
            "binding": "id"
        },
        {
            "name": "quizQuestion",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.attempts.index": [],
    "admin.attempts.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.tags.index": [],
    "admin.tags.ids": [],
    "admin.tags.create": [],
    "admin.tags.bulkDestroy": [],
    "admin.tags.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.tags.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.tags.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.tags.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.tagSubjects.index": [],
    "admin.question-reports.index": [],
    "admin.question-reports.update-status": [
        {
            "name": "id",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
