import * as React from "react";
import { Head, router } from "@inertiajs/react";
import AdminLayout from "@/layouts/admin";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { SmartPagination } from "@/components/common/SmartPagination";
import { Search, Eye, Users, BookOpen, Clock } from "lucide-react";
import { route } from "ziggy-js";

interface Subject {
    id: number;
    name: string;
}

interface TargetStudent {
    id: number;
    name: string;
}

interface Quiz {
    id: number;
    title: string;
    total_questions: number;
    time_limit_minutes: number | null;
    created_at: string;
    subject: {
        id: number;
        name: string;
    } | null;
    target_student: {
        id: number;
        name: string;
    } | null;
    creator: {
        id: number;
        name: string;
    } | null;
    strategy: string;
    subject_ids: number[] | null;
    attempt_count: number;
}

interface Props {
    quizzes: {
        data: Quiz[];
        current_page: number;
        last_page: number;
        per_page: number;
        total: number;
        from: number;
        to: number;
        links: Array<{
            url: string | null;
            label: string;
            active: boolean;
        }>;
        prev_page_url: string | null;
        next_page_url: string | null;
    };
    strategies: Record<string, string>;
    subjects: Subject[];
    targetStudents: TargetStudent[];
    filters: {
        search?: string;
        strategy?: string;
        target_student_id?: string;
        subject_id?: string;
    };
}

const strategyColors: Record<string, string> = {
    worst_performing: "bg-red-100 text-red-800",
    never_attempted: "bg-blue-100 text-blue-800",
    recently_incorrect: "bg-orange-100 text-orange-800",
    weak_subjects: "bg-purple-100 text-purple-800",
    mixed: "bg-green-100 text-green-800",
};

const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
    });
};

export default function Adaptive({
    quizzes,
    strategies,
    subjects,
    targetStudents,
    filters,
}: Props) {
    const [search, setSearch] = React.useState(filters.search || "");
    const [strategy, setStrategy] = React.useState(filters.strategy || "");
    const [subjectId, setSubjectId] = React.useState(filters.subject_id || "");
    const [targetStudentId, setTargetStudentId] = React.useState(
        filters.target_student_id || ""
    );

    const applyFilters = () => {
        const params: Record<string, string> = {};
        if (search) params.search = search;
        if (strategy) params.strategy = strategy;
        if (subjectId) params.subject_id = subjectId;
        if (targetStudentId) params.target_student_id = targetStudentId;

        router.get(route("admin.quizzes.adaptive"), params, {
            preserveState: true,
            preserveScroll: true,
        });
    };

    const clearFilters = () => {
        setSearch("");
        setStrategy("");
        setSubjectId("");
        setTargetStudentId("");
        router.get(route("admin.quizzes.adaptive"));
    };

    const handlePageChange = (url: string | null) => {
        if (url) {
            router.visit(url, {
                preserveState: true,
                preserveScroll: true,
            });
        }
    };

    const getStrategyColor = (strategyKey: string) => {
        return strategyColors[strategyKey] || "bg-gray-100 text-gray-800";
    };

    return (
        <AdminLayout
            breadcrumbs={[
                { title: "Dashboard", href: "/admin" },
                { title: "Quizzes", href: "/admin/quizzes" },
                {
                    title: "Student Adaptive Quizzes",
                    href: "/admin/quizzes/adaptive",
                },
            ]}
        >
            <Head title="Student Adaptive Quizzes" />
            <div className="p-6">
                <div className="mb-6">
                    <h1 className="text-3xl font-bold">
                        Student Adaptive Quizzes
                    </h1>
                    <p className="text-muted-foreground mt-2">
                        Browse adaptive quizzes generated by students
                    </p>
                </div>

                {/* Filters */}
                <Card className="mb-6">
                    <CardHeader>
                        <CardTitle>Filters</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="search">Search</Label>
                                <div className="relative">
                                    <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                                    <Input
                                        id="search"
                                        placeholder="Search by title, student..."
                                        value={search}
                                        onChange={(e) =>
                                            setSearch(e.target.value)
                                        }
                                        onKeyDown={(e) => {
                                            if (e.key === "Enter") {
                                                applyFilters();
                                            }
                                        }}
                                        className="pl-8"
                                    />
                                </div>
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="strategy">Strategy</Label>
                                <Select
                                    value={strategy}
                                    onValueChange={setStrategy}
                                >
                                    <SelectTrigger id="strategy">
                                        <SelectValue placeholder="All strategies" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="">
                                            All strategies
                                        </SelectItem>
                                        {Object.entries(strategies).map(
                                            ([key, label]) => (
                                                <SelectItem
                                                    key={key}
                                                    value={key}
                                                >
                                                    {label}
                                                </SelectItem>
                                            )
                                        )}
                                    </SelectContent>
                                </Select>
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="subject">Subject</Label>
                                <Select
                                    value={subjectId}
                                    onValueChange={setSubjectId}
                                >
                                    <SelectTrigger id="subject">
                                        <SelectValue placeholder="All subjects" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="">
                                            All subjects
                                        </SelectItem>
                                        {subjects.map((subject) => (
                                            <SelectItem
                                                key={subject.id}
                                                value={String(subject.id)}
                                            >
                                                {subject.name}
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="target_student">
                                    Target Student
                                </Label>
                                <Select
                                    value={targetStudentId}
                                    onValueChange={setTargetStudentId}
                                >
                                    <SelectTrigger id="target_student">
                                        <SelectValue placeholder="All students" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="">
                                            All students
                                        </SelectItem>
                                        {targetStudents.map((student) => (
                                            <SelectItem
                                                key={student.id}
                                                value={String(student.id)}
                                            >
                                                {student.name}
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                            </div>
                        </div>

                        <div className="flex justify-end space-x-2 mt-4">
                            <Button variant="outline" onClick={clearFilters}>
                                Clear
                            </Button>
                            <Button onClick={applyFilters}>
                                Apply Filters
                            </Button>
                        </div>
                    </CardContent>
                </Card>

                {/* Quizzes Table */}
                <Card>
                    <CardHeader>
                        <CardTitle>
                            Adaptive Quizzes ({quizzes.total || 0})
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        {quizzes.data.length === 0 ? (
                            <div className="text-center py-12">
                                <p className="text-muted-foreground">
                                    No adaptive quizzes found.
                                </p>
                            </div>
                        ) : (
                            <>
                                <div className="overflow-x-auto">
                                    <Table>
                                        <TableHeader>
                                            <TableRow>
                                                <TableHead>Title</TableHead>
                                                <TableHead>
                                                    Target Student
                                                </TableHead>
                                                <TableHead>Creator</TableHead>
                                                <TableHead>Strategy</TableHead>
                                                <TableHead>Subject</TableHead>
                                                <TableHead>Questions</TableHead>
                                                <TableHead>Attempts</TableHead>
                                                <TableHead>Created</TableHead>
                                                <TableHead className="text-right">
                                                    Actions
                                                </TableHead>
                                            </TableRow>
                                        </TableHeader>
                                        <TableBody>
                                            {quizzes.data.map((quiz) => (
                                                <TableRow key={quiz.id}>
                                                    <TableCell className="font-medium">
                                                        {quiz.title}
                                                    </TableCell>
                                                    <TableCell>
                                                        {quiz.target_student ? (
                                                            <div className="flex items-center">
                                                                <Users className="mr-2 h-4 w-4 text-muted-foreground" />
                                                                {
                                                                    quiz
                                                                        .target_student
                                                                        .name
                                                                }
                                                            </div>
                                                        ) : (
                                                            <span className="text-muted-foreground">
                                                                -
                                                            </span>
                                                        )}
                                                    </TableCell>
                                                    <TableCell>
                                                        {quiz.creator ? (
                                                            <span>
                                                                {
                                                                    quiz.creator
                                                                        .name
                                                                }
                                                            </span>
                                                        ) : (
                                                            <span className="text-muted-foreground">
                                                                -
                                                            </span>
                                                        )}
                                                    </TableCell>
                                                    <TableCell>
                                                        <Badge
                                                            className={getStrategyColor(
                                                                quiz.strategy ||
                                                                    ""
                                                            )}
                                                        >
                                                            {quiz.strategy
                                                                ? strategies[
                                                                      quiz
                                                                          .strategy
                                                                  ] ||
                                                                  quiz.strategy
                                                                : "-"}
                                                        </Badge>
                                                    </TableCell>
                                                    <TableCell>
                                                        {quiz.subject ? (
                                                            <div className="flex items-center">
                                                                <BookOpen className="mr-2 h-4 w-4 text-muted-foreground" />
                                                                {
                                                                    quiz.subject
                                                                        .name
                                                                }
                                                            </div>
                                                        ) : (
                                                            <span className="text-muted-foreground">
                                                                Multiple
                                                            </span>
                                                        )}
                                                    </TableCell>
                                                    <TableCell>
                                                        <div className="flex items-center">
                                                            {
                                                                quiz.total_questions
                                                            }
                                                            {quiz.time_limit_minutes && (
                                                                <>
                                                                    <Clock className="ml-2 mr-1 h-3 w-3 text-muted-foreground" />
                                                                    <span className="text-sm text-muted-foreground">
                                                                        {
                                                                            quiz.time_limit_minutes
                                                                        }
                                                                        m
                                                                    </span>
                                                                </>
                                                            )}
                                                        </div>
                                                    </TableCell>
                                                    <TableCell>
                                                        {quiz.attempt_count}
                                                    </TableCell>
                                                    <TableCell className="text-sm text-muted-foreground">
                                                        {formatDate(
                                                            quiz.created_at
                                                        )}
                                                    </TableCell>
                                                    <TableCell className="text-right">
                                                        <Button
                                                            variant="ghost"
                                                            size="sm"
                                                            onClick={() =>
                                                                router.visit(
                                                                    route(
                                                                        "admin.quizzes.show",
                                                                        quiz.id
                                                                    )
                                                                )
                                                            }
                                                        >
                                                            <Eye className="mr-2 h-4 w-4" />
                                                            View
                                                        </Button>
                                                    </TableCell>
                                                </TableRow>
                                            ))}
                                        </TableBody>
                                    </Table>
                                </div>

                                <SmartPagination
                                    currentPage={quizzes.current_page}
                                    totalPages={quizzes.last_page}
                                    onPageChange={(page) => {
                                        const url = quizzes.links.find(
                                            (link) =>
                                                link.label === String(page) &&
                                                link.url
                                        )?.url;
                                        if (url) handlePageChange(url);
                                    }}
                                    prevPageUrl={quizzes.prev_page_url}
                                    nextPageUrl={quizzes.next_page_url}
                                    onUrlChange={handlePageChange}
                                />
                            </>
                        )}
                    </CardContent>
                </Card>
            </div>
        </AdminLayout>
    );
}
